<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [1]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    import numpy as np
    if n == 0:
        return 0
    elif n < 0:
        return 'n must be positive'
    else:
        ax = np.arange(1,n+1)
        return np.prod(ax)            
        # np.prod(array)  -->  returns the product of all elements in an array

In [2]:
# Test

print(factorial(0))
print(factorial(-2))
print(factorial(5))

0
n must be positive
120


In [3]:
import numpy as np
np.cumprod(np.array([1,2,3,4]))
# np.cumprod(array)

array([ 1,  2,  6, 24])

In [4]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    import numpy as np
    if n == 0:
        return 0
    elif n < 0:
        return 'n must be positive'
    else:
        ay = np.arange(1,n+1)
        return np.cumprod(ay)

In [5]:
# Test

print(all_factorials(0))
print(all_factorials(-2))
print(all_factorials(3))
print(all_factorials(5))

0
n must be positive
[1 2 6]
[  1   2   6  24 120]


<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [6]:
def get_pct_changes(file_name):
    import numpy as np
    data = np.genfromtxt(file_name,delimiter=",") # Load data from a file
    df = data[np.logical_not(np.isnan(data))] # Remove NaN values
    pct_changes = np.diff(df)/df[:-1]  # Calculate the pct_changes
    return pct_changes

In [7]:
# Test

get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, one-day percent change to the file 
<li>Groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each of the groups



In [8]:
datafile = "apple.csv"
import pandas as pd
import numpy as np
df = pd.read_csv('apple.csv',na_values='null')

# Adds a column called 'One-Day percent change' to the file
df['One-Day Pct_Change'] = df['Adj Close'].pct_change()

# Group by function
def GroupColFunc(df, ind, col):
    if df[col].loc[ind] > 0.025:
        return 'High+'
    elif df[col].loc[ind] >= 0:
        return 'Low+'
    elif df[col].loc[ind] >= -0.025:
        return 'Low-'
    elif df[col].loc[ind] < -0.025:
        return 'High-'
    else:
        return None

# Apply the function
grouped = df.groupby(lambda x: GroupColFunc(df, x, 'One-Day Pct_Change'))

# Report the size and the mean of each of the groups
print(grouped.size())
print(grouped.mean())

High+    1391
High-    1210
Low+     3536
Low-     3140
dtype: int64
       Adj Close  One-Day Pct_Change
High+   8.652295            0.045705
High-   8.289065           -0.044220
Low+   23.738642            0.009879
Low-   24.183470           -0.011171


In [9]:
df

Date   Adj Close  One-Day Pct_Change
0     1980-12-12    0.421597                 NaN
1     1980-12-15    0.399601           -0.052173
2     1980-12-16    0.370272           -0.073396
3     1980-12-17    0.379437            0.024752
4     1980-12-18    0.390436            0.028988
...          ...         ...                 ...
9273  2017-09-20  156.070007           -0.016758
9274  2017-09-21  153.389999           -0.017172
9275  2017-09-22  151.889999           -0.009779
9276  2017-09-25  150.550003           -0.008822
9277  2017-09-26  153.139999            0.017204

[9278 rows x 3 columns]